services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  backend:
    container_name: backend
    build: /var/www/nextcommerce-backend
    ports:
      - "8080:3000"
    networks:
      - postgres
    restart: unless-stopped

  admin:
    container_name: admin
    build: /var/www/nextcommerce-admin
    environment:
      - NEXT_PUBLIC_API_URL=http://37.120.176.218:3000
    ports:
      - "3000:3000"
    restart: unless-stopped

    #frontend2:
    #  container_name: nextjs-frontend2
    #  build: /var/www/nextcommerce-frontend
    #   environment:
    #   - NEXT_PUBLIC_API_URL=http://api:3000
    #ports:
    #   - "3002:3000"
    # restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: