spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/next-commerce
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true